### ISSUE TITLE
会议页面“大会宗旨”、“往届活动回顾”、“大会概况”、“大会亮点”组件

### ISSUE THREAD

**Issue by PapayaHUANG** [freeCodeCamp-China/city#13]
具体布局如下：
![image](https://github.com/freeCodeCamp-China/city/assets/70144378/82aaa78f-cfc5-475e-a5e6-934332f51743)

注意：
- 不要沿用原始代码的写法，把数据单独拎出来和渲染逻辑分离
- 由于内容比较简单，我就只提了一个 issue，需要的可以分多个 pr （一个组件一个PR ）来做这个 issue

原始数据在 **conf-archive** 这个文件夹里

**Comment by TechQuery** [comment]
> 原始数据在 **conf-archive** 这个文件夹里

添加了 **Git 子模块**后似乎没把子模块拉下来，文件夹里面是空的。
