### ISSUE TITLE
修改网页标签 title 和 logo

### ISSUE THREAD

**Issue by d-ethan3** [freeCodeCamp-China/city#24]
修改之前
![title](https://github.com/freeCodeCamp-China/city/assets/33822639/239f839f-fc64-4e14-bb5f-d757e26c40b8)
修改之后
![old_title](https://github.com/freeCodeCamp-China/city/assets/33822639/8520d694-555a-4d26-a158-1b7e7eea8f52)

建议 title 为 freecodecamp 中文社区

**Comment by TechQuery** [comment]
> 修改之前 ![title](https://user-images.githubusercontent.com/33822639/259753427-239f839f-fc64-4e14-bb5f-d757e26c40b8.png) 修改之后 ![old_title](https://user-images.githubusercontent.com/33822639/259753827-8520d694-555a-4d26-a158-1b7e7eea8f52.png)
> 
> 建议 title 为 freecodecamp 中文社区

大小写规范：freeCodeCamp（遵循 JavaScript **标识符命名**的**小驼峰规范**）

**Comment by TechQuery** [comment]
## 网页图标修改点位

https://github.com/freeCodeCamp-China/city/blob/96ccd2e179b53bf9ff984fea0e623dc887a3be6f/pages/_document.tsx#L7

## 网页标题参考代码

https://github.com/freeCodeCamp-China/city/blob/96ccd2e179b53bf9ff984fea0e623dc887a3be6f/pages/organizer/index.tsx#L12
