### ISSUE TITLE
将 ⌈头像⌋ 和 ⌈内容⌋ 组件放在首页

### ISSUE THREAD

**Issue by d-ethan3** [freeCodeCamp-China/city#25]
并渲染出全部数据

**Comment by TechQuery** [comment]
讲师还是志愿者头像？什么内容？什么数据？

**Comment by d-ethan3** [comment]
> 讲师还是志愿者头像？什么内容？什么数据？

和原网页一样，在主页展示 【社区组织者】【演讲嘉宾】【合作企业】
内容样式：
![index](https://github.com/freeCodeCamp-China/city/assets/33822639/d76d2ae9-5cfe-4a75-9f1f-5fbb40932177)

原数据在 https://github.com/freeCodeCamp-China/city/blob/main/old/index.js

**Comment by huoyueyuyuan** [comment]
![1691937724200](https://github.com/freeCodeCamp-China/city/assets/22514503/d7dd898b-5222-4b79-a405-7d789e34249e)

**Comment by huoyueyuyuan** [comment]
主页方案：
1、显示一个城市列表  ： 图标  + 城市名称。 样式 参照 社区组织者 样式， 图标在上， 城市名称在下。
 图标引用地址：https://d33wubrfki0l68.cloudfront.net/2f7693e1933ac514c960f51ceae72c91c6716eb2/b2efd/img/fcc_primary_small.svg
2、点击 图标， 切换到不同的城市。 城市展示内容，先参照当前图片。
