### ISSUE TITLE
会议页面图片未显示

### ISSUE THREAD

**Issue by d-ethan3** [freeCodeCamp-China/city#26]
![bug01](https://github.com/freeCodeCamp-China/city/assets/33822639/bf4841aa-1f43-446d-998d-b007ebbab501)

**Comment by huoyueyuyuan** [comment]
feat: ConferencePage compoments : Guest & OrganizationInfo ; optimize :ConferenceBase #21
这个分支代码 代码通过后，可以直接解决了图片展示问题。
做 第1个issues的时候， 不太懂，没将图片拷贝到项目中，

**Comment by TechQuery** [comment]
@huoyueyuyuan 此处有一个需要改进的点 #27
